### ISSUE TITLE
lauch error:" NotImplementedError"

### ISSUE THREAD

**Issue by jasoncow007** [sinano1107/sd-webui-auto-tweet#3]
*** Error calling: C:\sd-webui-aki-v4\extensions\sd-webui-auto-tweet\scripts\extension.py/title
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "C:\sd-webui-aki-v4\modules\scripts.py", line 77, in title
        raise NotImplementedError()
    NotImplementedError

**Comment by jasoncow007** [comment]
and conflict with extention sd-webui-neutral-prompt

**Comment by RodgerE1** [comment]
---
*** Error completing request
*** Arguments: ('task(0sq19332gyu9f5e)', ' grey aliens,<lora:xl_more_art-full_v1:1>,<lora:alienxl:1>,', 'ugly,deformed,noisy,blurry,low contrast,cheerful,optimistic,vibrant,colorful,anime,cartoon,graphic,text,painting,crayon,graphite,abstract,glitch,deformed,mutated,ugly,disfigured,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,amaamateur, autograph, bad anatomy, bad art, bad illustration, bad proportions, beginner, beyond the borders, blank background, blurry, body out of frame, boring, clashing colors, cloned face, confusing composition, cropped, cut off, deformed, dehydrated, disfigured, distorted face, draft, dull, error, extra arms, extra fingers, extra legs, extra limbs, flat, fused fingers, grainy, green, gross proportions, inconsistent lighting, inconsistent shading, incorrect perspective, jpeg artifacts, lack of background, lack of detail, lack of depth, lack of dynamism, lack of focal point, lack of originality, long neck, low contrast, low quality, lowres, malformed limbs, missing arms, missing legs, mismatched colors, monotonous, morbid, mutated hands, mutation, obscure, overly complex, overly simplistic, over-saturated, overexposed, pixelated, poor lighting, poor texture, poorly drawn background, poorly drawn face, poorly drawn feet, poorly drawn hands, poorly executed concept, signature, stiff pose, text, tiling, too many fingers, ugly, under-saturated, underexposed, unappealing color palette, unbalanced composition, unclear, unfinished, unfocused, uninteresting subject, unnatural colors, unnatural pose, unrealistic proportions, username, watermark, worst quality,Amputee, Autograph, Bad anatomy, Bad art, Bad illustration, Bad proportions, Beginner, Beyond the borders, Blank background, Blurry, Body out of frame, Boring, Branding, Clashing colors, Cloned face, Confusing composition, Cropped, Cut off, Deformed, Dehydrated, Disfigured, Distorted, Distorted face, Draft, Dull, Duplicate, Duplicated features, Error, Extra arms, Extra fingers, Extra hands, Extra legs, Extra limbs, Fault, Flat, Flaw, Fused fingers, Grains, Grainy, Green, Gross proportions, Hazy, Identifying mark, Improper scale, Inconsistent lighting, Inconsistent shading, Incorrect perspective, Incorrect physiology, Incorrect ratio, Indistinct, Jpeg artifacts, Kitsch, Lack of background, Lack of detail, Lack of depth, Lack of dynamism, Lack of focal point, Lack of originality, Logo, Long neck, Low contrast, Low quality, Low resolution, Lowres, Macabre, Malformed, Malformed limbs, Mark, Missing arms, Missing fingers, Missing hands, Missing legs, Mismatched colors, Mistake, Monotonous, Morbid, Mutated hands, Mutation, Mutilated, Obscure, Off-screen, Over-saturated, Overexposed, Out of frame, Outside the picture, Overly complex, Overly simplistic, Pixelated, Poor lighting, Poor texture, Poorly drawn background, Poorly drawn face, Poorly drawn feet, Poorly drawn hands, Poorly executed concept, Print, Repellent, Replicate, Reproduce, Revolting dimensions, Script, Shortened, Sign, Signature, Split image, Squint, Stiff pose, Storyboard, Text, Tiling, Too many fingers, Trimmed, Ugly, Under-saturated, Underexposed, Unappealing color palette, Unattractive, Unbalanced composition, Unclear, Unfinished, Unfocused, Uninteresting subject, Unnatural colors, Unnatural pose, Unreal engine, Unrealistic proportions, Unsightly, Username, Watermark, Worst quality, Written language\n', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 1024, 1024, False, 0.7, 2, 'Latent', 20, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000245FDADDF30>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, False, False, 'base', True, -1.0, True, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.animatediff_ui.AnimateDiffProcess object at 0x00000245FDAB5C60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000245FDAB4BB0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000245FDAB7E80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000245D093B7F0>, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'CodeFormer', 1, 1, 'None', 1, 1, ['After Upscaling/Before Restore Face'], 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, False, False, '#000000', False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 39, in processing_process_images_hijack
        cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 184, in get_cn_batches
        units = external_code.get_all_units_in_processing(p)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 202, in get_all_units_in_processing
        return get_all_units(p.scripts, p.script_args)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 211, in get_all_units
        cn_script = find_cn_script(script_runner)
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 449, in find_cn_script
        if is_cn_script(script):
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 458, in is_cn_script
        return script.title().lower() == 'controlnet'
      File "C:\Users\rodge\StabilityMatrix\Packages\Stable Diffusion WebUI\modules\scripts.py", line 77, in title
        raise NotImplementedError()
    NotImplementedError

---

**Comment by shadowstar4222** [comment]
did you ever figure this out?
